name: tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    name: Test Suite
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v4
      - name: Install Dependencies
        run: sudo apt-get update && sudo apt-get install --no-install-recommends clang make
      - name: Build files
        run: make
      - name: Run tests
        run: make all_tests | tee test_results.txt
      - name: Print test results
        run: cat test_results.txt
